source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CAUMessage_Example', :exclusive => true do
  pod 'CAUMessage', :path => '../'
end

target 'CAUMessage_Tests', :exclusive => true do
  pod 'CAUMessage', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
